# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'porousBafflePressureAMIFvPatchField'

sources = Split("""
constraint/jumpCyclicAMI/jumpCyclicAMIFvPatchFields.cpp
derived/fixedJumpAMI/fixedJumpAMIFvPatchFields.cpp
derived/porousBafflePressureAMI/porousBafflePressureAMIFvPatchFields.cpp
""")

caelus_inc = [
'transportModels',
'turbulenceModels',
'thermophysicalModels/basic/lnInclude',
'thermophysicalModels/specie/lnInclude',
'transportModels/incompressible/singlePhaseTransportModel'
]

caelus_libs = [
'core',
'basicThermophysicalModels',
'specie',
'compressibleTurbulenceModel',
'incompressibleTurbulenceModel'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
